can_bitrate: null
can_interface: null
command_timeout_sec: null
driver_watchdog_sec: null
driver_watchdog_verified: false
estop_adapter: std_msgs/Bool
ros1_master_uri: null
status_adapter: std_msgs/String JSON
stop_angular_radps: null
stop_linear_mps: null
stop_timeout_sec: null
