cmake_minimum_required(VERSION 3.8)
project(agt_epoch_rpp_controller)
set(CMAKE_CXX_STANDARD 17)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(rclcpp_lifecycle REQUIRED)
find_package(nav2_core REQUIRED)
find_package(nav2_regulated_pure_pursuit_controller REQUIRED)
find_package(nav2_costmap_2d REQUIRED)
find_package(pluginlib REQUIRED)
find_package(tf2_ros REQUIRED)
find_package(agt_navigation_interfaces REQUIRED)
add_library(epoch_rpp SHARED src/epoch_rpp_controller.cpp)
target_include_directories(epoch_rpp PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include> $<INSTALL_INTERFACE:include>)
ament_target_dependencies(epoch_rpp rclcpp rclcpp_lifecycle nav2_core nav2_regulated_pure_pursuit_controller nav2_costmap_2d pluginlib tf2_ros agt_navigation_interfaces)
pluginlib_export_plugin_description_file(nav2_core controller_plugin.xml)
install(TARGETS epoch_rpp LIBRARY DESTINATION lib)
install(DIRECTORY include/ DESTINATION include)
ament_export_include_directories(include)
ament_export_libraries(epoch_rpp)
ament_package()
